#!/bin/sh

HOOK=$1
shift # Drop hook name from arguments
PROJECT_ROOT=$(git rev-parse --show-toplevel)

# Run local hook if exists
if [ -e "$PROJECT_ROOT/.git/hooks/$HOOK" ]; then
  $PROJECT_ROOT/.git/hooks/$HOOK "$@"
else
  exit 0
fi
